### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by lKhyst** [tigierrei/Skinner#1]
When I try /sk upload SKIN png NAME returns this for me on console:

[22:06:47] [pool-37-thread-1/INFO]: [0;33;1mUploading skin...[m
[22:06:48] [pool-37-thread-1/INFO]: [0;32;1mSkin data generated.[m
[22:06:48] [pool-37-thread-1/INFO]: disguises.yml has been found and loaded.
[22:06:48] [pool-37-thread-1/INFO]: [0;31;1mException while generating skin, see console for details: java.lang.NullPointerException[m
[22:06:48] [pool-37-thread-1/INFO]: [0;31;1mPlease make sure the image is a valid skin texture and try again.[m
[22:06:48] [pool-37-thread-1/WARN]: [Skinner] Exception while generating skin
java.lang.RuntimeException: java.lang.NullPointerException
	at org.mineskin.MineskinClient.handleResponse(MineskinClient.java:257) ~[?:?]
	at org.mineskin.MineskinClient.lambda$generateUpload$2(MineskinClient.java:182) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at it.tigierrei.skinner.commands.SkinnerCommand$uploadSkin$1.done(SkinnerCommand.kt:114) ~[?:?]
	at org.mineskin.MineskinClient.handleResponse(MineskinClient.java:253) ~[?:?]
	... 4 more

**Comment by tigierrei** [comment]
Do you have a file called SKIN.png in /plugins/Skinner/skins ? If not that's why you are getting this error. If the file exists make sure it is a PNG and not a JPEG

**Comment by tigierrei** [comment]
Since this problem is a week, I close it, imagining that you have solved your problem.
